[package]
name = "fqlib"
version = "0.1.0"
authors = ["Michael Macias <michael.macias@stjude.org>"]
license = "Apache-2.0"
autobins = false

[[bin]]
name = "fq"
path = "src/main.rs"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
bloom = { git = "https://github.com/zaeleus/bloom.git" }
clap = "2.31.2"
env_logger = "0.5.10"
flate2 = "1.0.1"
log = "0.4.1"
noodles = { git = "https://github.com/zaeleus/noodles.git" }
rand = "0.6.0"
